const ANIMALS = [
    'alligator',
    'anteater',
    'armadillo',
    'axolotl',
    'badger',
    'bat',
    'beaver',
    'buffalo',
    'cat',
    'camel',
    'capybara',
    'chameleon',
    'cheetah',
    'chinchilla',
    'chipmunk',
    'chupacabra',
    'cormorant',
    'coyote',
    'crow',
    'dingo',
    'dinosaur',
    'duck',
    'doggo',
    'elephant',
    'ferret',
    'fox',
    'frog',
    'giraffe',
    'gopher',
    'gorilla',
    'grizzly',
    'hedgehog',
    'hippo',
    'hyena',
    'ibex',
    'ifrit*',
    'iguana',
    'jackal',
    'jackalope',
    'kangaroo',
    'koala',
    'kraken',
    'leopard',
    'lemur',
    'liger',
    'lizard',
    'loris',
    'manatee',
    'mink',
    'monkey',
    'moose',
    'narwhal',
    'nyancat',
    'orangutan',
    'otter',
    'panda',
    'penguin',
    'platypus',
    'python',
    'quagga',
    'rabbit',
    'raccoon',
    'rhino',
    'sheep',
    'shrew',
    'skunk',
    'snek',
    'squirrel',
    'tiger',
    'turtle',
    'walrus',
    'whale',
    'wolf',
    'wolverine',
    'wombat'
]

export function randomAnimal() {
    return ANIMALS[Math.floor(Math.random() * ANIMALS.length)]
}

// generate a random 3-word combination of animals
export function generateRandomGameId() {
    return `${randomAnimal()}-${randomAnimal()}-${randomAnimal()}`
}
